### ISSUE TITLE
Add Program Name field

### ISSUE THREAD

**Issue by dan-brewster** [csasf/members#10]
Per Steve, some members use different/anglicized names in the program than they do in "official" things like signing waivers and so on. 

We should support a new string field on Member, "preferred_name" and add a textbox for it on the form. We should also add it to the member#show page, if present.

Additionally, add a one-time script to populate the fields based on existing names -- "{first} {last}".

**Comment by wenley** [comment]
Suggestion: the column name as `program_name` - I've seen `preferred_name` used as what a person prefers to be called in person, which is potentially distinct from their legal name and their preferred name in print.

**Comment by dan-brewster** [comment]
Good idea! Let's do that.
