### ISSUE TITLE
When creating new performance set, add option to rollover all members 

### ISSUE THREAD

**Issue by dan-brewster** [csasf/members#15]
A common task will be creating a new performance set for an existing group (i.e., Civic Symphony Winter 2017). When doing so, there should be an option that will copy all members who played in that set and add them to the new set, all with playing status of "Unconfirmed". All set-member-instrument linkings should remain the same. All rotating flags should be cleared. The option should be checked by default. (the option does not need to be saved in the database, just used to trigger execution of a script when submitted)

**Comment by wenley** [comment]
I'd suggest making a separate ruby class to perform this action. Something like:
```
class CopyPerformanceSetMembers
  def call(ensemble, performance_set_name)
    new_performance = PerformanceSet.create!(ensemble: ensemble, name: performance_set_name)
    # Copy over members
  end
end
```

Helps keep the controllers from getting bloated, since this is very specialized for a particular action.

**Comment by dan-brewster** [comment]
Sounds good to me. We have plenty of options on how to do this.

**Comment by dan-brewster** [comment]
This no longer makes sense with our processes. (members must explicitly sign up or be signed up for each set)
