### ISSUE TITLE
Add ability to send email to arbitrary groups of members

### ISSUE THREAD

**Issue by dan-brewster** [csasf/members#20]
We will want to enable simple email sending to arbitrary groups of members., i.e. per performance set, per instrument, combinations thereof, etc. This issue is for creating a page/form to send a simple email to a selected group.

The goal eventually is to retire our various other methods of sending emails and use this exclusively.

**Comment by wenley** [comment]
Genuine question: Why do we want to retire other methods of sending emails? Keeping the current google groups lets people continue to use familiar UIs and prevents us from having to build whole other UI. Plus allowing any social announcements (vs. "official" announcements) would then lead to adding an authorization layer.

Granted, I haven't had any exposure to what I imagine might be a painful process of administrating the lists. It'd be cool have it "auto-synced" simply by using the same DB, but I'd rather not over-engineer this code base. (Too many horror stories...)

**Comment by dan-brewster** [comment]
Yeah, I know this is a bit of a black hole here. Our current email solutions do not work well -- the Yahoo group is an unmoderated collection of random players from the past 15 years, and the other two groups have these private lists that are kept. Section leaders keep their own lists, sometimes, and many don't keep track well at all. This has been a pain point I've heard from many people.

My thought process is that since I was already needing to send emails here to individual users, it would probably make sense to try and use the system for sending emails to everybody. It may end up being a non-starter, but I think it's worth exploring. 

Potentially at some point we could try having automatic email lists set up via the system, so you could email 'violas-sfcs@members.sfcivicsymphony.org` and it would route correctly, which would allow you to use a client you're familiar with, but I'd rather be more clear about who is being emailed.

**Comment by dan-brewster** [comment]
Oh, and this would be purely for one-way communication. I think we're to the point where most social communication happens on social media or outside of email, and I wouldn't be opposed to cutting that off (it only happens for the Civic Symphony now anyway, since the other groups don't have public email lists)

**Comment by dan-brewster** [comment]
This was completed and is generally working fine.
