### ISSUE TITLE
Prohibit duplicate `performance_set` to `member` relations

### ISSUE THREAD

**Issue by dan-brewster** [csasf/members#32]
Each member can only have one `member_set` per `performance_set`. Again, I think this is currently enforced on the client and should be enforced on the server, too.

**Comment by wenley** [comment]
This is pretty easy to do with a uniqueness index. I'll do it now.

**Comment by dan-brewster** [comment]
Awesome!

**Comment by dan-brewster** [comment]
This is done, thanks @wenley!
