### ISSUE TITLE
Fix section vs instrument data model

### ISSUE THREAD

**Issue by dan-brewster** [csasf/members#35]
I keep forgetting about this one because it's so terrible.

We need to be able to distinguish between sections and instruments for many purposes. While a member may play Violin, their section may be Violin I or Violin II, and we need to be able to know that. This is basically not an issue for any other section in the orchestra, since we're not going to care if someone is Clarinet I or Clarinet II.

Originally I was thinking of adding a field for this to `set_member_instrument`, but I'm not sure I like that, and in light of #22 that may not be the right path anyway.

This is fairly urgent.

**Comment by wenley** [comment]
Just to clarify on "since we're not going to care if someone is Clarinet I or Clarinet II." - is that because it's irrelevant for program purposes? For attendance + rehearsals?

**Comment by dan-brewster** [comment]
Yeah, there's nothing we need to keep track of right now around that. When figuring out concert instrumentation (a big use of this system starting next set), we'll just do it by instrument. Generally everyone assumes that if you have three clarinets, there's one each of I, II, and III.

The need may arise at some future point, though, I just don't know of an immediate need.

**Comment by dan-brewster** [comment]
Ended up adding a field to `set_member_instrument` because other options were unnecessarily complex.
